### ISSUE TITLE
Add Video Duration to Photos API

### ISSUE THREAD

**Issue by asteven5** [google/java-photoslibrary#46]
The Google Photos API does not return video duration. I would expect the API to return the length of the clip in minutes and seconds.

It would be very useful for a variety of reasons in different applications. Please make this available.

**Comment by jfschmakeit** [comment]
The Google Photos Library API does not return the duration of videos, that is why the client library also does not currently support this functionality. 

There is a feature request open on the Library API issue tracker, please "star" it (or use the `+1` button) on this request here to draw attention to it and be notified of any updates: https://issuetracker.google.com/123979425 

Thank you! 

(I'm closing this issue as this is a feature request for the API itself, rather than this particular client library.)
